import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, sendPasswordResetEmail, signOut } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import { getFirestore, doc, getDoc, collection, addDoc, query, where, getDocs, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyCI4sasDSZOf8txLyeOl6RI-szFkW9gZx8',authDomain:'home-8e824.firebaseapp.com',projectId:'home-8e824',storageBucket:'home-8e824.firebasestorage.app',messagingSenderId:'798232728283',appId:'1:798232728283:web:4488a32b4f13c0141a72fe'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app); const ADMIN_EMAIL='thanatchaiyok@gmail.com'; const BACKEND_URL=''; let user=null,profile={};
const $=id=>document.getElementById(id); const esc=v=>String(v??'-').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function msg(id,t,c=''){$(id).textContent=t;$(id).className='message '+c} function isAdmin(){return user?.email?.toLowerCase()===ADMIN_EMAIL.toLowerCase()||profile.role==='admin'}
function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));$(id).classList.add('active-page');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo(0,0)}
async function load(){const s=await getDoc(doc(db,'users',user.uid));profile=s.exists()?s.data():{email:user.email,name:user.email};$('welcomeName').textContent=profile.name||profile.fullName||user.email;$('userRole').textContent=isAdmin()?'แอดมิน':'สมาชิก';$('dashStatus').textContent=profile.status||'ปกติ';document.querySelectorAll('.admin-only').forEach(x=>x.style.display=isAdmin()?'flex':'none');renderProfile();renderBirthday();loadBills();loadRequests()}
function renderProfile(){const p=profile,fs=[['ชื่อ-สกุล',p.name||p.fullName],['ชื่อเล่น',p.nickname],['เลขบัตร',p.idCard],['หลังบัตร',p.backCard],['รหัสบัตรธนาคาร',p.bankCode],['เลขบัญชีธนาคาร',p.bankAccount],['อายุ',p.age],['สถานะ',p.status],['ที่อยู่',p.address],['Passport',p.passport],['ทะเบียนบ้าน',p.housebook],['สูติบัตร',p.birthCertificate],['รายได้ต่อเดือน/อาชีพ',p.incomeJob]];$('profileCard').innerHTML=fs.map(x=>`<div class="profile-item"><span>${esc(x[0])}</span><b>${esc(x[1]||'-')}</b></div>`).join('')}
function renderBirthday(){const b=profile.birthDate||profile.birthday;if(!b){$('birthdayDate').textContent='ยังไม่ได้บันทึก';$('birthdayCountdown').textContent='-';return}const d=new Date(b),n=new Date();let next=new Date(n.getFullYear(),d.getMonth(),d.getDate());if(next<n)next.setFullYear(n.getFullYear()+1);const days=Math.ceil((next-n)/86400000);$('birthdayDate').textContent=d.toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric'});$('birthdayCountdown').textContent=`อีก ${days} วัน`;$('dashBirthday').textContent=`${days} วัน`}
async function loadBills(){try{const s=await getDocs(query(collection(db,'bills'),where('uid','==',user.uid)));const a=s.docs.map(d=>d.data()).sort((x,y)=>String(y.month||'').localeCompare(String(x.month||'')));$('billList').innerHTML=a.length?a.map(r=>`<div class="bill"><div><b>${esc(r.month||r.period||'บิลค่าไฟ')}</b><small>${esc(r.status||'')}</small></div><strong>${esc(r.amount??'-')} บาท</strong></div>`).join(''):'<div class="empty">ยังไม่มีข้อมูลบิลค่าไฟ</div>';$('dashBill').textContent=a[0]?.amount!=null?`${a[0].amount} บาท`:'-'}catch(e){$('billList').innerHTML='<div class="empty">ยังไม่มีข้อมูลบิลค่าไฟ</div>'}}
async function loadRequests(){try{const s=await getDocs(query(collection(db,'requests'),where('uid','==',user.uid)));const a=s.docs.map(d=>d.data()).sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0));$('requestList').innerHTML=a.length?a.map(r=>`<div class="request"><div><b>${esc(r.title)}</b><small>${r.type==='repair'?'แจ้งซ่อม':'แจ้งยืม'} • ${esc(r.detail)}</small></div><span class="status-pill">${esc(r.status||'รอดำเนินการ')}</span></div>`).join(''):'<div class="empty">ยังไม่มีรายการ</div>'}catch(e){$('requestList').innerHTML='<div class="empty">ยังไม่มีรายการ</div>'}}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();msg('loginMsg','กำลังเข้าสู่ระบบ...');try{await signInWithEmailAndPassword(auth,$('loginEmail').value.trim(),$('loginPassword').value);msg('loginMsg','เข้าสู่ระบบสำเร็จ','ok')}catch(e){msg('loginMsg','อีเมลหรือรหัสผ่านไม่ถูกต้อง','error')}});$('forgotBtn').addEventListener('click',async()=>{const x=$('loginEmail').value.trim();if(!x)return msg('loginMsg','กรุณาใส่อีเมลก่อน','error');try{await sendPasswordResetEmail(auth,x);msg('loginMsg','ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว','ok')}catch(e){msg('loginMsg','ไม่สามารถส่งลิงก์ได้','error')}});$('logoutBtn').onclick=()=>signOut(auth);
document.querySelectorAll('[data-page],[data-page-go]').forEach(b=>b.onclick=()=>show(b.dataset.page||b.dataset.pageGo));
$('requestForm').onsubmit=async e=>{e.preventDefault();msg('requestMsg','กำลังบันทึก...');try{await addDoc(collection(db,'requests'),{uid:user.uid,email:user.email,type:$('requestType').value,title:$('requestTitle').value.trim(),detail:$('requestDetail').value.trim(),status:'รอดำเนินการ',createdAt:serverTimestamp()});e.target.reset();msg('requestMsg','ส่งรายการเรียบร้อยแล้ว','ok');loadRequests()}catch(x){msg('requestMsg','บันทึกไม่ได้ กรุณาตรวจสอบ Firestore rules','error')}};
$('memberForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return msg('memberMsg','ไม่มีสิทธิ์','error');if(!BACKEND_URL)return msg('memberMsg','ฟอร์มพร้อมแล้ว แต่การสร้างบัญชีจริงต้องเชื่อม Backend/Firebase Admin SDK ก่อน เพื่อความปลอดภัย','error');const data={email:$('memberEmail').value.trim(),idCard:$('f_idcard').value,backCard:$('f_backcard').value,name:$('f_name').value,nickname:$('f_nickname').value,bankCode:$('f_bankcode').value,bankAccount:$('f_bankaccount').value,age:$('f_age').value,status:$('f_status').value,address:$('f_address').value,passport:$('f_passport').value,housebook:$('f_housebook').value,birthCertificate:$('f_birthcert').value,incomeJob:$('f_income').value};try{const r=await fetch(BACKEND_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'createMember',data})});const j=await r.json();msg('memberMsg',j.message||'สร้างสมาชิกแล้ว','ok');e.target.reset()}catch(x){msg('memberMsg','เรียก Backend ไม่สำเร็จ','error')}};
$('lineContact').onclick=e=>{if($('lineContact').getAttribute('href')==='#'){e.preventDefault();$('lineHint').textContent='ยังไม่ได้ตั้งค่า LINE URL ใน app.js'}};
onAuthStateChanged(auth,async u=>{user=u;$('loading').classList.add('hidden');if(!u){$('authView').classList.remove('hidden');$('appView').classList.add('hidden')}else{$('authView').classList.add('hidden');$('appView').classList.remove('hidden');try{await load()}catch(e){profile={name:u.email};$('welcomeName').textContent=u.email}}});
