import {initializeApp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,sendPasswordResetEmail,signOut} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js';
import {getFirestore,doc,getDoc,setDoc,collection,addDoc,query,where,getDocs,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyCI4sasDSZOf8txLyeOl6RI-szFkW9cZx8',authDomain:'home-8e824.firebaseapp.com',projectId:'home-8e824',storageBucket:'home-8e824.firebasestorage.app',messagingSenderId:'798232728283',appId:'1:798232728283:web:4488a32b4f13c0141a72fe'};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);const ADMIN_EMAIL='thanatchaiyok@gmail.com';const LINE_URL='';let user=null,profile={};
const $=id=>document.getElementById(id);const esc=v=>String(v??'-').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function msg(id,t,c=''){$(id).textContent=t;$(id).className='message '+c}function isAdmin(){return profile.role==='admin'||user?.email?.toLowerCase()===ADMIN_EMAIL.toLowerCase()}function show(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));$(id)?.classList.add('active-page');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));window.scrollTo(0,0)}
async function load(){const s=await getDoc(doc(db,'users',user.uid));profile=s.exists()?s.data():{email:user.email,name:user.email,role:'member'};$('welcomeName').textContent=profile.name||profile.fullName||user.email;$('userRole').textContent=isAdmin()?'แอดมิน':'สมาชิก';$('dashStatus').textContent=profile.status||'ปกติ';document.querySelectorAll('.admin-only').forEach(x=>x.style.display=isAdmin()?'flex':'none');renderProfile();renderBirthday();await loadBills();await loadRequests();if(LINE_URL){$('lineContact').href=LINE_URL;$('lineHint').textContent=''}else{$('lineHint').textContent='ผู้ดูแลระบบยังไม่ได้ตั้งค่า LINE URL'}}
function renderProfile(){const p=profile,fs=[['ชื่อ-สกุล',p.name||p.fullName],['ชื่อเล่น',p.nickname],['เลขบัตร',p.idCard],['หลังบัตร',p.backCard],['รหัสบัตรธนาคาร',p.bankCode],['เลขบัญชีธนาคาร',p.bankAccount],['อายุ',p.age],['สถานะ',p.status],['ที่อยู่',p.address],['Passport',p.passport],['ทะเบียนบ้าน',p.housebook],['สูติบัตร',p.birthCertificate],['รายได้ต่อเดือน/อาชีพ',p.incomeJob]];$('profileCard').innerHTML=fs.map(x=>`<div class="profile-item"><span>${esc(x[0])}</span><b>${esc(x[1]||'-')}</b></div>`).join('')}
function renderBirthday(){const b=profile.birthDate||profile.birthday;if(!b){$('birthdayDate').textContent='ยังไม่ได้บันทึก';$('birthdayCountdown').textContent='-';$('dashBirthday').textContent='-';return}const d=new Date(b+'T00:00:00'),n=new Date();let next=new Date(n.getFullYear(),d.getMonth(),d.getDate());if(next<new Date(n.getFullYear(),n.getMonth(),n.getDate()))next.setFullYear(n.getFullYear()+1);const days=Math.max(0,Math.ceil((next-new Date(n.getFullYear(),n.getMonth(),n.getDate()))/86400000));$('birthdayDate').textContent=d.toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric'});$('birthdayCountdown').textContent=days===0?'🎉 วันนี้วันเกิด!':`อีก ${days} วัน`;$('dashBirthday').textContent=days===0?'วันนี้':`${days} วัน`}
async function loadBills(){try{const s=await getDocs(query(collection(db,'bills'),where('uid','==',user.uid)));const a=s.docs.map(d=>({id:d.id,...d.data()})).sort((x,y)=>String(y.month||'').localeCompare(String(x.month||'')));$('billList').innerHTML=a.length?a.map(r=>`<div class="bill"><div><b>${esc(r.month||r.period||'บิลค่าไฟ')}</b><small>${esc(r.status||'')}</small></div><strong>${esc(r.amount??'-')} บาท</strong></div>`).join(''):'<div class="empty">ยังไม่มีข้อมูลบิลค่าไฟ</div>';$('dashBill').textContent=a[0]?.amount!=null?`${a[0].amount} บาท`:'-'}catch(e){$('billList').innerHTML='<div class="empty">ไม่สามารถโหลดบิลได้';$('dashBill').textContent='-'}}
async function loadRequests(){try{const s=await getDocs(query(collection(db,'requests'),where('uid','==',user.uid)));const a=s.docs.map(d=>({id:d.id,...d.data()})).sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0));$('requestList').innerHTML=a.length?a.map(r=>`<div class="request"><div><b>${esc(r.title)}</b><small>${r.type==='repair'?'แจ้งซ่อม':'แจ้งยืม'} • ${esc(r.detail)}</small></div><span class="status-pill">${esc(r.status||'รอดำเนินการ')}</span></div>`).join(''):'<div class="empty">ยังไม่มีรายการ</div>'}catch(e){$('requestList').innerHTML='<div class="empty">ไม่สามารถโหลดรายการได้' }}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();msg('loginMsg','กำลังเข้าสู่ระบบ...');try{await signInWithEmailAndPassword(auth,$('loginEmail').value.trim(),$('loginPassword').value);msg('loginMsg','เข้าสู่ระบบสำเร็จ','ok')}catch(e){msg('loginMsg','อีเมลหรือรหัสผ่านไม่ถูกต้อง','error')}});$('forgotBtn').onclick=async()=>{const x=$('loginEmail').value.trim();if(!x)return msg('loginMsg','กรุณาใส่อีเมลก่อน','error');try{await sendPasswordResetEmail(auth,x);msg('loginMsg','ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว','ok')}catch(e){msg('loginMsg','ไม่สามารถส่งลิงก์ได้','error')}};$('logoutBtn').onclick=()=>signOut(auth);
document.querySelectorAll('[data-page],[data-page-go]').forEach(b=>b.onclick=()=>show(b.dataset.page||b.dataset.pageGo));
$('requestForm').onsubmit=async e=>{e.preventDefault();msg('requestMsg','กำลังบันทึก...');try{await addDoc(collection(db,'requests'),{uid:user.uid,email:user.email,type:$('requestType').value,title:$('requestTitle').value.trim(),detail:$('requestDetail').value.trim(),status:'รอดำเนินการ',createdAt:serverTimestamp()});e.target.reset();msg('requestMsg','ส่งรายการเรียบร้อยแล้ว','ok');await loadRequests()}catch(x){msg('requestMsg','บันทึกไม่ได้ กรุณาตรวจสอบ Firestore Rules','error')}};
async function createMember(data){const url=`https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=${encodeURIComponent(firebaseConfig.apiKey)}`;const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:data.email,password:data.password,returnSecureToken:true})});const j=await r.json();if(!r.ok)throw new Error(j.error?.message||'สร้างบัญชีไม่สำเร็จ');return j}
$('memberForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return msg('memberMsg','ไม่มีสิทธิ์','error');const data={email:$('memberEmail').value.trim(),password:$('memberPassword').value,idCard:$('f_idcard').value.trim(),backCard:$('f_backcard').value.trim(),name:$('f_name').value.trim(),nickname:$('f_nickname').value.trim(),bankCode:$('f_bankcode').value.trim(),bankAccount:$('f_bankaccount').value.trim(),age:$('f_age').value,status:$('f_status').value.trim(),birthDate:$('f_birthdate').value,address:$('f_address').value.trim(),passport:$('f_passport').value.trim(),housebook:$('f_housebook').value.trim(),birthCertificate:$('f_birthcert').value.trim(),incomeJob:$('f_income').value.trim(),role:'member'};try{msg('memberMsg','กำลังสร้างบัญชี...');const created=await createMember(data);const token=created.idToken;const r=await fetch(`https://firestore.googleapis.com/v1/projects/${firebaseConfig.projectId}/databases/(default)/documents/users/${created.localId}?key=${encodeURIComponent(firebaseConfig.apiKey)}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({fields:Object.fromEntries(Object.entries(data).filter(([k])=>k!=='password').map(([k,v])=>[k,{stringValue:String(v??'')}]))})});if(!r.ok)throw new Error('สร้างบัญชีสำเร็จแต่บันทึกข้อมูลสมาชิกไม่สำเร็จ');e.target.reset();msg('memberMsg','สร้างบัญชีสมาชิกเรียบร้อยแล้ว','ok')}catch(x){msg('memberMsg',x.message||'สร้างสมาชิกไม่สำเร็จ','error')}};
$('billForm').onsubmit=async e=>{e.preventDefault();if(!isAdmin())return msg('billMsg','ไม่มีสิทธิ์','error');try{await addDoc(collection(db,'bills'),{uid:$('billUid').value.trim(),month:$('billMonth').value.trim(),amount:Number($('billAmount').value),status:$('billStatus').value.trim(),createdAt:serverTimestamp()});e.target.reset();msg('billMsg','บันทึกบิลเรียบร้อยแล้ว','ok')}catch(x){msg('billMsg','บันทึกบิลไม่ได้ กรุณาตรวจสอบ Firestore Rules','error')}};
$('lineContact').onclick=e=>{if(!LINE_URL){e.preventDefault();$('lineHint').textContent='กรุณาตั้งค่า LINE_URL ใน app2.js ก่อนใช้งานปุ่มนี้'}};
onAuthStateChanged(auth,async u=>{user=u;$('loading').classList.add('hidden');if(!u){$('authView').classList.remove('hidden');$('appView').classList.add('hidden')}else{$('authView').classList.add('hidden');$('appView').classList.remove('hidden');try{await load()}catch(e){console.error(e);profile={name:u.email,role:'member'};$('welcomeName').textContent=u.email}}});