/** Home Manager NK25/3 - Google Apps Script backend
 * Deploy as Web App: Execute as Me, access for users who can reach the app.
 * Put all secrets in Script Properties, never in this file.
 * Required properties:
 * FIREBASE_WEB_API_KEY, FIREBASE_PROJECT_ID, ADMIN_EMAIL, ADMIN_SECRET,
 * SHEET_ID, LINE_CHANNEL_ACCESS_TOKEN, LINE_OA_URL, LINE_PROFILE_URL
 */
const P = PropertiesService.getScriptProperties();
const MEMBERS = 'Members', REQUESTS = 'Requests', BILLS = 'Bills', LOGS = 'Logs';
const MEMBER_HEADERS = ['uid','email','idCard','backCard','name','nickname','bankCode','bankAccount','age','status','address','passport','housebook','birthCertificate','incomeJob','birthDate','role','lineUserId','createdAt','updatedAt'];
const REQUEST_HEADERS = ['id','uid','email','type','title','detail','status','createdAt','updatedAt'];
const BILL_HEADERS = ['id','uid','month','amount','status','createdAt'];

function json(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function sheet(name, headers){const ss=SpreadsheetApp.openById(P.getProperty('SHEET_ID'));let s=ss.getSheetByName(name);if(!s)s=ss.insertSheet(name);if(s.getLastRow()===0)s.appendRow(headers);return s}
function rows(name,headers){const s=sheet(name,headers);if(s.getLastRow()<2)return [];return s.getDataRange().getValues().slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]])))}
function append(name,headers,obj){const s=sheet(name,headers);s.appendRow(headers.map(h=>obj[h]??''))}
function now(){return new Date().toISOString()}
function auth_(e){const h=e?.headers||{};const token=(h.Authorization||h.authorization||'').replace(/^Bearer\s+/,'');if(!token)throw Error('ต้องเข้าสู่ระบบ');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+encodeURIComponent(P.getProperty('FIREBASE_WEB_API_KEY')),{method:'post',contentType:'application/json',payload:JSON.stringify({idToken:token}),muteHttpExceptions:true});const j=JSON.parse(r.getContentText());if(!r.getResponseCode().toString().startsWith('2')||!j.users?.[0])throw Error('Firebase token ไม่ถูกต้อง');const u=j.users[0];const members=rows(MEMBERS,MEMBER_HEADERS);const m=members.find(x=>String(x.uid)===String(u.localId));const isAdmin=String(u.email||'').toLowerCase()===String(P.getProperty('ADMIN_EMAIL')||'').toLowerCase()||m?.role==='admin';return {u,m,isAdmin}}
function doGet(e){try{const a=e.parameter?.action||'health';if(a==='health')return json({ok:true,service:'Home Manager NK25/3'});return json({ok:false,error:'Unknown action'})}catch(x){return json({ok:false,error:x.message})}}
function doPost(e){try{const body=JSON.parse(e.postData?.contents||'{}');const action=body.action||'';if(action==='adminBootstrap')return adminBootstrap_(body);const a=auth_(e);switch(action){case 'me':return json({ok:true,profile:a.m||{uid:a.u.localId,email:a.u.email,name:a.u.email,role:a.isAdmin?'admin':'member'}});case 'requests':return json({ok:true,items:rows(REQUESTS,REQUEST_HEADERS).filter(x=>a.isAdmin||x.uid===a.u.localId).sort((x,y)=>String(y.createdAt).localeCompare(String(x.createdAt)))});case 'createRequest':return createRequest_(a,body);case 'bills':return json({ok:true,items:rows(BILLS,BILL_HEADERS).filter(x=>a.isAdmin||x.uid===a.u.localId).sort((x,y)=>String(y.month).localeCompare(String(x.month)))});case 'adminCreateMember':if(!a.isAdmin)throw Error('ไม่มีสิทธิ์แอดมิน');return adminCreateMember_(body);case 'adminAddBill':if(!a.isAdmin)throw Error('ไม่มีสิทธิ์แอดมิน');return adminAddBill_(body);case 'adminMembers':if(!a.isAdmin)throw Error('ไม่มีสิทธิ์แอดมิน');return json({ok:true,items:rows(MEMBERS,MEMBER_HEADERS).map(x=>({...x,idCard:mask_(x.idCard),backCard:mask_(x.backCard),bankCode:mask_(x.bankCode),bankAccount:mask_(x.bankAccount)}))});case 'linkLine':return linkLine_(a,body);default:throw Error('ไม่รู้จัก action')}}catch(x){return json({ok:false,error:x.message||'เกิดข้อผิดพลาด'})}}
function createRequest_(a,b){const id=Utilities.getUuid();const r={id,uid:a.u.localId,email:a.u.email,type:b.type==='repair'?'repair':'borrow',title:String(b.title||'').slice(0,120),detail:String(b.detail||'').slice(0,2000),status:'รอดำเนินการ',createdAt:now(),updatedAt:now()};if(!r.title||!r.detail)throw Error('กรุณากรอกหัวข้อและรายละเอียด');append(REQUESTS,REQUEST_HEADERS,r);notifyAdmin_('📩 แจ้ง'+(r.type==='repair'?'ซ่อม':'ยืม')+' ใหม่\n'+r.title+'\n'+r.detail);return json({ok:true,item:r})}
function adminCreateMember_(b){if(!b.email||!b.password||!b.name)throw Error('ต้องมีอีเมล รหัสผ่าน และชื่อ-สกุล');const key=P.getProperty('FIREBASE_WEB_API_KEY');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(key),{method:'post',contentType:'application/json',payload:JSON.stringify({email:b.email,password:b.password,returnSecureToken:false}),muteHttpExceptions:true});const j=JSON.parse(r.getContentText());if(r.getResponseCode()>=300)throw Error(j.error?.message||'สร้าง Firebase account ไม่สำเร็จ');const allowed={uid:j.localId,email:b.email,idCard:b.idCard||'',backCard:b.backCard||'',name:b.name,nickname:b.nickname||'',bankCode:b.bankCode||'',bankAccount:b.bankAccount||'',age:b.age||'',status:b.status||'ปกติ',address:b.address||'',passport:b.passport||'',housebook:b.housebook||'',birthCertificate:b.birthCertificate||'',incomeJob:b.incomeJob||'',birthDate:b.birthDate||'',role:'member',lineUserId:'',createdAt:now(),updatedAt:now()};append(MEMBERS,MEMBER_HEADERS,allowed);return json({ok:true,uid:j.localId})}
function adminAddBill_(b){if(!b.uid||!b.month)throw Error('กรุณาระบุ UID และรอบบิล');const r={id:Utilities.getUuid(),uid:String(b.uid),month:String(b.month),amount:Number(b.amount||0),status:String(b.status||'รอชำระ'),createdAt:now()};append(BILLS,BILL_HEADERS,r);const m=rows(MEMBERS,MEMBER_HEADERS).find(x=>x.uid===r.uid);if(m?.lineUserId)linePush_(m.lineUserId,'🧾 บิลค่าไฟ\nรอบ: '+r.month+'\nยอด: '+r.amount+' บาท\nสถานะ: '+r.status);return json({ok:true,item:r})}
function linkLine_(a,b){const uid=String(b.lineUserId||'');if(!uid)throw Error('ไม่พบ LINE user ID');const s=sheet(MEMBERS,MEMBER_HEADERS),data=s.getDataRange().getValues();for(let i=1;i<data.length;i++)if(String(data[i][0])===String(a.u.localId)){data[i][17]=uid;data[i][19]=now();s.getRange(i+1,1,data[i].length).setValues([data[i]]);return json({ok:true})}throw Error('ไม่พบสมาชิก')}
function mask_(v){const s=String(v||'');return s.length<5?'••••':s.slice(0,2)+'••••'+s.slice(-2)}
function notifyAdmin_(text){const adminLine=P.getProperty('ADMIN_LINE_USER_ID');if(adminLine)linePush_(adminLine,text)}
function linePush_(userId,text){const token=P.getProperty('LINE_CHANNEL_ACCESS_TOKEN');if(!token)throw Error('ยังไม่ได้ตั้งค่า LINE_CHANNEL_ACCESS_TOKEN');UrlFetchApp.fetch('https://api.line.me/v2/bot/message/push',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+token},payload:JSON.stringify({to:userId,messages:[{type:'text',text:String(text).slice(0,5000)}]}),muteHttpExceptions:true})}
function birthdayReminder(){const ms=rows(MEMBERS,MEMBER_HEADERS),today=new Date();const md=Utilities.formatDate(today,Session.getScriptTimeZone(),'MM-dd');ms.forEach(m=>{if(!m.birthDate||!m.lineUserId)return;const d=new Date(m.birthDate);const b=Utilities.formatDate(d,Session.getScriptTimeZone(),'MM-dd');if(b===md)linePush_(m.lineUserId,'🎂 สุขสันต์วันเกิด '+(m.name||'สมาชิก Home Manager')+' ขอให้มีความสุขมาก ๆ');});}
function adminBootstrap_(b){if(String(b.secret||'')!==String(P.getProperty('ADMIN_SECRET')||''))throw Error('ADMIN_SECRET ไม่ถูกต้อง');const email=P.getProperty('ADMIN_EMAIL');const key=P.getProperty('FIREBASE_WEB_API_KEY');if(!email||!key)throw Error('ตั้งค่า Script Properties ก่อน');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(key),{method:'post',contentType:'application/json',payload:JSON.stringify({email,password:String(b.password||''),returnSecureToken:false}),muteHttpExceptions:true});const j=JSON.parse(r.getContentText());if(r.getResponseCode()>=300&&j.error?.message!=='EMAIL_EXISTS')throw Error(j.error?.message||'สร้างแอดมินไม่สำเร็จ');return json({ok:true,message:'ใช้บัญชีแอดมินเข้าสู่ Firebase แล้ว จากนั้นสร้างสมาชิกจากหน้า Admin'})}
