/** Home Manager NK25/3 backend */
const P=PropertiesService.getScriptProperties(),MEMBERS='Members',REQUESTS='Requests',BILLS='Bills';const MH=['uid','email','idCard','backCard','name','nickname','bankCode','bankAccount','age','status','address','passport','housebook','birthCertificate','incomeJob','birthDate','role','lineUserId','createdAt','updatedAt'],RH=['id','uid','email','type','title','detail','status','createdAt','updatedAt'],BH=['id','uid','month','amount','status','createdAt'];const out=o=>ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON),now=()=>new Date().toISOString();
function sh(n,h){const s=SpreadsheetApp.openById(P.getProperty('SHEET_ID'));let x=s.getSheetByName(n);if(!x)x=s.insertSheet(n);if(x.getLastRow()===0)x.appendRow(h);return x}function rows(n,h){const s=sh(n,h);if(s.getLastRow()<2)return[];return s.getDataRange().getValues().slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]])))}function add(n,h,o){sh(n,h).appendRow(h.map(k=>o[k]??''))}
function firebaseUser_(token){if(!token)throw Error('ต้องเข้าสู่ระบบ');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:lookup?key='+encodeURIComponent(P.getProperty('FIREBASE_WEB_API_KEY')),{method:'post',contentType:'application/json',payload:JSON.stringify({idToken:token}),muteHttpExceptions:true});const j=JSON.parse(r.getContentText());if(r.getResponseCode()>=300||!j.users?.[0])throw Error('Firebase token ไม่ถูกต้อง');return j.users[0]}
function auth_(token){const u=firebaseUser_(token),m=rows(MEMBERS,MH).find(x=>String(x.uid)===String(u.localId));return{u,m,isAdmin:String(u.email||'').toLowerCase()===String(P.getProperty('ADMIN_EMAIL')||'').toLowerCase()||m?.role==='admin'}}
function action_(a,b){const A=auth_(b.token||'');if(a==='requests'&&b.type)return createRequest_(A,b);switch(a){case'me':return out({ok:true,profile:A.m||{uid:A.u.localId,email:A.u.email,name:A.u.email,role:A.isAdmin?'admin':'member'}});case'requests':return out({ok:true,items:rows(REQUESTS,RH).filter(x=>A.isAdmin||x.uid===A.u.localId).sort((x,y)=>String(y.createdAt).localeCompare(String(x.createdAt)))});case'bills':return out({ok:true,items:rows(BILLS,BH).filter(x=>A.isAdmin||x.uid===A.u.localId).sort((x,y)=>String(y.month).localeCompare(String(x.month)))});case'admin_members':if(!A.isAdmin)throw Error('ไม่มีสิทธิ์แอดมิน');return createMember_(b);case'admin_bills':if(!A.isAdmin)throw Error('ไม่มีสิทธิ์แอดมิน');return addBill_(b);default:throw Error('ไม่รู้จัก action: '+a)}}
function createRequest_(A,b){const r={id:Utilities.getUuid(),uid:A.u.localId,email:A.u.email,type:b.type==='repair'?'repair':'borrow',title:String(b.title||'').trim(),detail:String(b.detail||'').trim(),status:'รอดำเนินการ',createdAt:now(),updatedAt:now()};if(!r.title||!r.detail)throw Error('กรุณากรอกหัวข้อและรายละเอียด');add(REQUESTS,RH,r);notifyAdmin_('📩 แจ้ง'+(r.type==='repair'?'ซ่อม':'ยืม')+' ใหม่\n'+r.title+'\n'+r.detail);return out({ok:true,item:r})}
function createMember_(b){if(!b.email||!b.password||!b.name)throw Error('ต้องมีอีเมล รหัสผ่าน และชื่อ-สกุล');const r=UrlFetchApp.fetch('https://identitytoolkit.googleapis.com/v1/accounts:signUp?key='+encodeURIComponent(P.getProperty('FIREBASE_WEB_API_KEY')),{method:'post',contentType:'application/json',payload:JSON.stringify({email:b.email,password:b.password,returnSecureToken:false}),muteHttpExceptions:true});const j=JSON.parse(r.getContentText());if(r.getResponseCode()>=300)throw Error(j.error?.message||'สร้างบัญชีไม่สำเร็จ');const o={uid:j.localId,email:b.email,idCard:b.idCard||'',backCard:b.backCard||'',name:b.name,nickname:b.nickname||'',bankCode:b.bankCode||'',bankAccount:b.bankAccount||'',age:b.age||'',status:b.status||'ปกติ',address:b.address||'',passport:b.passport||'',housebook:b.housebook||'',birthCertificate:b.birthCertificate||'',incomeJob:b.incomeJob||'',birthDate:b.birthDate||'',role:'member',lineUserId:'',createdAt:now(),updatedAt:now()};add(MEMBERS,MH,o);return out({ok:true,uid:j.localId})}
function addBill_(b){if(!b.uid||!b.month)throw Error('กรุณาระบุ UID และรอบบิล');const r={id:Utilities.getUuid(),uid:String(b.uid),month:String(b.month),amount:Number(b.amount||0),status:String(b.status||'รอชำระ'),createdAt:now()};add(BILLS,BH,r);const m=rows(MEMBERS,MH).find(x=>x.uid===r.uid);if(m?.lineUserId)linePush_(m.lineUserId,'🧾 บิลค่าไฟ\nรอบ: '+r.month+'\nยอด: '+r.amount+' บาท\nสถานะ: '+r.status);return out({ok:true,item:r})}
function doGet(e){try{const p=e.parameter||{};if(p.hook&&p.hook===P.getProperty('LINE_WEBHOOK_SECRET'))return out({ok:true,webhook:'ready'});return action_(p.action||'health',{token:p.token||''})}catch(x){return out({ok:false,error:x.message})}}
function doPost(e){try{const b=JSON.parse(e?.postData?.contents||'{}');if(b.events&&e.parameter?.hook===P.getProperty('LINE_WEBHOOK_SECRET'))return lineWebhookBody_(b);return action_(b.action||'',b)}catch(x){return out({ok:false,error:x.message})}}
function lineWebhookBody_(b){(b.events||[]).forEach(ev=>{const uid=ev.source?.userId;if(uid&&ev.type==='follow')linePush_(uid,'ยินดีต้อนรับสู่ Home Manager NK25/3\nกรุณาเชื่อมบัญชี LINE กับเว็บไซต์ตามขั้นตอนของระบบ')});return out({ok:true})}
function notifyAdmin_(text){const id=P.getProperty('ADMIN_LINE_USER_ID');if(id)linePush_(id,text)}function linePush_(uid,text){const t=P.getProperty('LINE_CHANNEL_ACCESS_TOKEN');if(!t)throw Error('ยังไม่ได้ตั้งค่า LINE_CHANNEL_ACCESS_TOKEN');UrlFetchApp.fetch('https://api.line.me/v2/bot/message/push',{method:'post',contentType:'application/json',headers:{Authorization:'Bearer '+t},payload:JSON.stringify({to:uid,messages:[{type:'text',text:String(text).slice(0,5000)}]}),muteHttpExceptions:true})}
function birthdayReminder(){const today=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'MM-dd');rows(MEMBERS,MH).forEach(m=>{if(!m.birthDate||!m.lineUserId)return;const md=Utilities.formatDate(new Date(m.birthDate),Session.getScriptTimeZone(),'MM-dd');if(md===today)linePush_(m.lineUserId,'🎂 สุขสันต์วันเกิด '+(m.name||'สมาชิก Home Manager')+' ขอให้มีความสุขมาก ๆ')})}
