import { adminDb } from "@/lib/firebase-admin";
import { notFound } from "next/navigation";
import type { AppUser, Bill, Repair, Borrow } from "@/lib/types";
import BillCard from "@/components/BillCard";
import RevealField from "@/components/RevealField";

export default async function MemberDetailPage({ params }: { params: { id: string } }) {
  const doc = await adminDb.collection("users").doc(params.id).get();
  if (!doc.exists) notFound();
  const member = doc.data() as AppUser;
  const [billsSnap, repairsSnap, borrowsSnap] = await Promise.all([
    adminDb.collection("bills").where("userId", "==", params.id).orderBy("year", "desc").limit(6).get(),
    adminDb.collection("repairs").where("userId", "==", params.id).orderBy("createdAt", "desc").limit(5).get(),
    adminDb.collection("borrows").where("userId", "==", params.id).orderBy("borrowDate", "desc").limit(5).get(),
  ]);
  const bills = billsSnap.docs.map((d) => d.data() as Bill); const repairs = repairsSnap.docs.map((d) => d.data() as Repair); const borrows = borrowsSnap.docs.map((d) => d.data() as Borrow);
  return <div className="max-w-3xl space-y-6"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center rounded-full bg-brand/10 text-xl font-semibold text-brand">{member.roomNumber}</div><div><h1 className="text-2xl font-semibold text-gray-900">{member.nameTH}</h1><p className="text-gray-500">{member.nameEN}</p></div></div><section className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="mb-4 font-medium text-gray-900">ข้อมูลติดต่อ</h2><dl className="grid grid-cols-2 gap-4 text-sm"><div><dt className="text-gray-500">เบอร์โทร</dt><dd className="font-medium">{member.phone || "—"}</dd></div><div><dt className="text-gray-500">LINE ID</dt><dd className="font-medium">{member.lineId || "—"}</dd></div><div><dt className="text-gray-500">วันเริ่มสัญญา</dt><dd className="font-medium">{member.startDate || "—"}</dd></div><div><dt className="text-gray-500">ค่าเช่าต่อเดือน</dt><dd className="font-medium">{member.monthlyRent?.toLocaleString() ?? "—"} บาท</dd></div></dl></section><section className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="mb-4 font-medium text-gray-900">เอกสารประจำตัว (แตะเพื่อดู)</h2><div className="grid grid-cols-1 gap-4 sm:grid-cols-3"><RevealField label="เลขบัตรประชาชน" value={member.idCard?.number || "—"} /><RevealField label="เลขพาสปอร์ต" value={member.passport?.number || "—"} /><RevealField label="เลขทะเบียนบ้าน" value={member.houseRegistration?.number || "—"} /></div></section><section className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="mb-4 font-medium text-gray-900">บิลไฟฟ้าล่าสุด</h2><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{bills.map((b) => <BillCard key={b.id} bill={b} />)}{bills.length === 0 && <p className="text-sm text-gray-500">ยังไม่มีบิล</p>}</div></section><section className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="mb-4 font-medium text-gray-900">แจ้งซ่อมล่าสุด</h2><ul className="space-y-2 text-sm">{repairs.map((r) => <li key={r.id} className="flex justify-between border-b border-gray-100 pb-2"><span>{r.type} — {r.description}</span><span className="text-gray-500">{r.status}</span></li>)}{repairs.length === 0 && <p className="text-gray-500">ยังไม่มีรายการแจ้งซ่อม</p>}</ul></section><section className="rounded-xl border border-gray-200 bg-white p-6"><h2 className="mb-4 font-medium text-gray-900">การยืมอุปกรณ์ล่าสุด</h2><ul className="space-y-2 text-sm">{borrows.map((b) => <li key={b.id} className="flex justify-between border-b border-gray-100 pb-2"><span>{b.item} x{b.quantity}</span><span className="text-gray-500">{b.status}</span></li>)}{borrows.length === 0 && <p className="text-gray-500">ยังไม่มีรายการยืม</p>}</ul></section></div>;
}
